language: lisp

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    # - LISP=clisp
    # - LISP=clisp32
    # - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    # CIM not available for CMUCL
    # - env: LISP=cmucl
    # free edition --- heap exhausted
    - env: LISP=allegro
    - env: LISP=abcl            # until lisp-namespace is updated
    # - env: LISP=clisp
    # - env: LISP=clisp32
    - env: LISP=ecl

# either use a local install.sh script or install it via curl. Feel
# free to simplify this section in your own .travis.yml file.
install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi     
  - git clone --depth=1 https://github.com/guicho271828/trivia.git ~/lisp/trivia
  - git clone --depth=1 https://github.com/guicho271828/type-i.git ~/lisp/type-i
  - git clone --depth=1 https://github.com/guicho271828/type-i.git ~/lisp/type-r #  for testing
  - git clone --depth=1 https://github.com/guicho271828/lisp-namespace.git ~/lisp/lisp-namespace

# this bit is just testing that travis correctly sets up ASDF to find
# systems placed somewhere within ~/lisp. You can remove this section
# in your own .travis.yml file.
before_script:
  - echo "(defsystem :dummy-cl-travis-system)" > ~/lisp/dummy-cl-travis-system.asd

script:
  - cl --eval '(progn (ql:quickload :fiveam)(load "testscr.lisp"))'
